# Generated by Django 4.2.16 on 2024-11-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchorages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchorage',
            name='seabed_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
