# Generated by Django 4.2.16 on 2024-11-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchorages', '0003_alter_bookmark_anchorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bookmarked_anchorages',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='anchorages.anchorage'),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
